export const name = 'dnd-5e';

const PLUGIN_ID = 'dnd-5e';
const PAGE_KEY = 'main-sheet';
const VERSION = 1;
export const ABILITIES = [['strength','Strength','STR'],['dexterity','Dexterity','DEX'],['constitution','Constitution','CON'],['intelligence','Intelligence','INT'],['wisdom','Wisdom','WIS'],['charisma','Charisma','CHA']];
export const SKILLS = [['acrobatics','Acrobatics','dexterity'],['animal-handling','Animal Handling','wisdom'],['arcana','Arcana','intelligence'],['athletics','Athletics','strength'],['deception','Deception','charisma'],['history','History','intelligence'],['insight','Insight','wisdom'],['intimidation','Intimidation','charisma'],['investigation','Investigation','intelligence'],['medicine','Medicine','wisdom'],['nature','Nature','intelligence'],['perception','Perception','wisdom'],['performance','Performance','charisma'],['persuasion','Persuasion','charisma'],['religion','Religion','intelligence'],['sleight-of-hand','Sleight of Hand','dexterity'],['stealth','Stealth','dexterity'],['survival','Survival','wisdom']];

export const abilityModifier = (score) => Math.floor((Number(score) - 10) / 2);
export const proficiencyBonus = (level) => 2 + Math.floor((Math.max(1, Number(level)) - 1) / 4);
export const proficiencyMultiplier = (state) => state === 'EXPERTISE' ? 2 : state === 'PROFICIENT' ? 1 : 0;
export const derivedModifier = (score, state, level) => abilityModifier(score) + proficiencyMultiplier(state) * proficiencyBonus(level);
export const signed = (value) => Number(value) >= 0 ? `+${Number(value)}` : String(Number(value));

export function normalizeCollection(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value) || value.version !== VERSION || !Array.isArray(value.entries)) return { version: VERSION, entries: [] };
  return { version: VERSION, entries: value.entries.filter((entry) => entry && typeof entry === 'object' && !Array.isArray(entry)) };
}

export function validateCollection(kind, value) {
  const required = {
    attacks: ['id','name','ability','proficiency','bonus','damage','damageType','notes'],
    equipment: ['id','name','quantity','equipped','notes'],
    features: ['id','name','source','description','usesCurrent','usesMaximum','reset'],
    'proficiencies-languages': ['id','name','type','notes'],
  }[kind];
  if (!required || !value || value.version !== VERSION || !Array.isArray(value.entries)) return false;
  return value.entries.every((entry) => {
    if (!entry || typeof entry !== 'object' || !required.every((key) => Object.hasOwn(entry, key)) || typeof entry.id !== 'string' || !entry.id) return false;
    if (kind === 'attacks') return typeof entry.name === 'string' && ABILITIES.some(([ability]) => ability === entry.ability) && ['NONE','PROFICIENT','EXPERTISE'].includes(entry.proficiency) && Number.isFinite(entry.bonus) && typeof entry.damage === 'string' && typeof entry.damageType === 'string' && typeof entry.notes === 'string';
    if (kind === 'equipment') return typeof entry.name === 'string' && Number.isFinite(entry.quantity) && typeof entry.equipped === 'boolean' && typeof entry.notes === 'string';
    if (kind === 'features') return typeof entry.name === 'string' && typeof entry.source === 'string' && typeof entry.description === 'string' && Number.isFinite(entry.usesCurrent) && Number.isFinite(entry.usesMaximum) && ['NONE','SHORT_REST','LONG_REST'].includes(entry.reset);
    return typeof entry.name === 'string' && ['LANGUAGE','ARMOR','WEAPON','TOOL','OTHER'].includes(entry.type) && typeof entry.notes === 'string';
  });
}

export function validateSpellcastingSources(value) {
  return Boolean(value && value.version === VERSION && Array.isArray(value.entries)) && value.entries.every((entry) => entry && typeof entry.id === 'string' && entry.id && typeof entry.name === 'string' && ABILITIES.some(([ability]) => ability === entry.ability) && Number.isFinite(entry.attackBonus) && Number.isFinite(entry.saveDcBonus) && typeof entry.notes === 'string');
}

export function validateSpells(value) {
  return Boolean(value && value.version === VERSION && Array.isArray(value.entries)) && value.entries.every((entry) => entry && typeof entry.id === 'string' && entry.id && typeof entry.name === 'string' && Number.isInteger(entry.level) && entry.level >= 0 && entry.level <= 9 && typeof entry.school === 'string' && typeof entry.sourceId === 'string' && typeof entry.prepared === 'boolean' && typeof entry.ritual === 'boolean' && typeof entry.concentration === 'boolean' && typeof entry.castingTime === 'string' && typeof entry.range === 'string' && typeof entry.components === 'string' && typeof entry.duration === 'string' && typeof entry.reference === 'string' && typeof entry.notes === 'string');
}

export function spellcastingSummary(source, abilityScore, level) {
  const base = abilityModifier(abilityScore) + proficiencyBonus(level);
  return { attackModifier: base + Number(source.attackBonus || 0), saveDc: 8 + base + Number(source.saveDcBonus || 0) };
}

function el(tag, className, text) { const result = document.createElement(tag); if (className) result.className = className; if (text !== undefined) result.textContent = text; return result; }
const asMap = (fields) => new Map(fields.map((field) => [field.key, field]));
const numberValue = (field, fallback = 0) => Number.isFinite(Number(field?.value)) ? Number(field.value) : fallback;
const canEdit = (field, context) => Boolean(context.permissions.canEdit && field?.capabilities?.writable);

function installStyles(root) {
  const style = el('style');
  style.textContent = `
  [data-dnd5e-sheet]{--ink:var(--foreground,#29221d);--muted:var(--muted-foreground,#6b625b);--paper:var(--background,#fffdf8);color:var(--ink);font-family:ui-sans-serif,system-ui,sans-serif}[data-dnd5e-sheet] *{box-sizing:border-box}
  [data-dnd5e-sheet] .sheet{display:grid;gap:1rem;max-width:88rem;margin:auto}[data-dnd5e-sheet] .panel{border:1px solid color-mix(in srgb,currentColor 24%,transparent);border-radius:.75rem;background:color-mix(in srgb,var(--paper) 96%,currentColor 4%);box-shadow:0 1px 2px #0001}
  [data-dnd5e-sheet] .header{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:1rem;align-items:center;padding:1rem 1.25rem;border-top:4px solid var(--primary,#7b2d26)}[data-dnd5e-sheet] h2,[data-dnd5e-sheet] h3{font-family:ui-serif,Georgia,serif}[data-dnd5e-sheet] h2{margin:0;font-size:clamp(1.5rem,4vw,2.4rem);line-height:1}[data-dnd5e-sheet] .kicker{margin:.3rem 0 0;color:var(--muted);font-size:.7rem;font-weight:800;letter-spacing:.13em;text-transform:uppercase}
  [data-dnd5e-sheet] .page-grid{display:grid;grid-template-columns:minmax(18rem,.72fr) minmax(22rem,1fr) minmax(20rem,.85fr);gap:1rem;align-items:start}[data-dnd5e-sheet] .column,[data-dnd5e-sheet] .stack,[data-dnd5e-sheet] .collection{display:grid;gap:.8rem}[data-dnd5e-sheet] .section{padding:.85rem}[data-dnd5e-sheet] h3{margin:0 0 .7rem;padding-bottom:.35rem;border-bottom:2px solid color-mix(in srgb,currentColor 45%,transparent);font-size:1rem;letter-spacing:.06em;text-transform:uppercase}
  [data-dnd5e-sheet] .label{font-size:.66rem;font-weight:850;letter-spacing:.09em;text-transform:uppercase}[data-dnd5e-sheet] input,[data-dnd5e-sheet] select,[data-dnd5e-sheet] textarea{width:100%;border:1px solid color-mix(in srgb,currentColor 27%,transparent);border-radius:.4rem;background:var(--paper);color:inherit;padding:.42rem .5rem;font:inherit}[data-dnd5e-sheet] :focus-visible{outline:3px solid var(--primary,#7b2d26);outline-offset:2px}[data-dnd5e-sheet] :disabled{opacity:.62;cursor:not-allowed}
  [data-dnd5e-sheet] .abilities{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}[data-dnd5e-sheet] .ability{display:grid;grid-template-columns:3.8rem minmax(0,1fr);gap:.55rem;padding:.65rem}[data-dnd5e-sheet] .score{display:grid;place-items:center;align-content:center}[data-dnd5e-sheet] .modifier{font-family:ui-serif,Georgia,serif;font-size:1.7rem;font-weight:850;line-height:1}[data-dnd5e-sheet] .score input{width:3.4rem;margin-top:.35rem;border-radius:999px;text-align:center;font-weight:800}
  [data-dnd5e-sheet] .derived-list{display:grid;gap:.24rem}[data-dnd5e-sheet] .derived{display:grid;grid-template-columns:1.8rem 2.5rem minmax(0,1fr) 3rem;gap:.25rem;align-items:center;font-size:.77rem}[data-dnd5e-sheet] .derived output{font-weight:850;text-align:center}[data-dnd5e-sheet] .prof{width:1.7rem;height:1.7rem;padding:0;border-radius:999px;font-size:0}[data-dnd5e-sheet] .prof option{font-size:initial}[data-dnd5e-sheet] .prof[data-state=PROFICIENT],[data-dnd5e-sheet] .prof[data-state=EXPERTISE]{background:var(--primary,#7b2d26);border-color:var(--primary,#7b2d26)}[data-dnd5e-sheet] .prof[data-state=EXPERTISE]{box-shadow:inset 0 0 0 4px var(--paper)}[data-dnd5e-sheet] .tag{color:var(--muted);font-size:.63rem}
  [data-dnd5e-sheet] .combat-top{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.55rem}[data-dnd5e-sheet] .stat{min-height:6.2rem;display:grid;place-items:center;align-content:center;gap:.35rem;padding:.65rem;text-align:center}[data-dnd5e-sheet] .stat output{font-family:ui-serif,Georgia,serif;font-size:1.65rem;font-weight:850}[data-dnd5e-sheet] .stat input{max-width:5rem;text-align:center;font-size:1.15rem;font-weight:800}[data-dnd5e-sheet] .two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}[data-dnd5e-sheet] .field{display:grid;gap:.28rem}
  [data-dnd5e-sheet] .entry{display:grid;gap:.45rem;padding:.65rem;border:1px solid color-mix(in srgb,currentColor 17%,transparent);border-radius:.55rem}[data-dnd5e-sheet] .entry-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.45rem}[data-dnd5e-sheet] .wide{grid-column:1/-1}[data-dnd5e-sheet] .actions{display:flex;justify-content:flex-end;gap:.45rem}[data-dnd5e-sheet] button{border:1px solid color-mix(in srgb,currentColor 25%,transparent);border-radius:.4rem;background:transparent;color:inherit;padding:.35rem .65rem;font:inherit;font-size:.75rem;font-weight:750;cursor:pointer}[data-dnd5e-sheet] .primary{background:var(--primary,#7b2d26);color:var(--primary-foreground,#fff);border-color:transparent}[data-dnd5e-sheet] .empty,[data-dnd5e-sheet] .status{color:var(--muted);font-size:.78rem}[data-dnd5e-sheet] .status{text-align:right;margin:0;min-height:1.2rem}[data-dnd5e-sheet] .status[data-error=true]{color:#b42318}
  @media(max-width:1050px){[data-dnd5e-sheet] .page-grid{grid-template-columns:minmax(18rem,.8fr) minmax(22rem,1.2fr)}[data-dnd5e-sheet] .page-grid>.column:last-child{grid-column:1/-1;grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:720px){[data-dnd5e-sheet] .header{grid-template-columns:1fr 1fr}[data-dnd5e-sheet] .header>:first-child{grid-column:1/-1}[data-dnd5e-sheet] .page-grid{grid-template-columns:1fr}[data-dnd5e-sheet] .page-grid>.column:last-child{grid-column:auto;grid-template-columns:1fr}}@media(max-width:440px){[data-dnd5e-sheet] .abilities,[data-dnd5e-sheet] .combat-top,[data-dnd5e-sheet] .entry-grid{grid-template-columns:1fr}[data-dnd5e-sheet] .wide{grid-column:auto}}
  `;
  root.appendChild(style);
}

function labeled(label, control, wide = false) { const wrapper = el('label', `field${wide ? ' wide' : ''}`); if (!control.hasAttribute('aria-label')) control.setAttribute('aria-label', label); wrapper.append(el('span','label',label), control); return wrapper; }

function inputFor(field, context, saved, type = 'number') {
  const control = el(type === 'textarea' ? 'textarea' : 'input'); if (type !== 'textarea') control.type = type;
  control.value = field?.value == null ? '' : String(field.value); control.disabled = !canEdit(field, context); control.setAttribute('aria-label', field?.label ?? 'Character field');
  if (field?.validation?.min !== undefined) control.min = field.validation.min; if (field?.validation?.max !== undefined) control.max = field.validation.max;
  control.addEventListener('change', async () => { if (!field || (type === 'number' && control.value === '')) return; const old = field.value; control.disabled = true; try { const updated = await context.updateField(field.id, type === 'number' ? Number(control.value) : control.value); field.value = updated.value; control.value = String(updated.value ?? ''); saved(null); } catch (error) { control.value = String(old ?? ''); saved(error); } finally { control.disabled = !canEdit(field, context); } });
  return control;
}

function selectFor(field, context, values, saved, compact = false) {
  const control = el('select', compact ? 'prof' : ''); for (const [value,label] of values) { const option = el('option','',label); option.value = value; control.appendChild(option); }
  control.value = String(field?.value ?? values[0][0]); control.dataset.state = control.value; control.disabled = !canEdit(field, context); control.setAttribute('aria-label', field?.label ?? 'Character field');
  control.addEventListener('change', async () => { const old = field.value; control.disabled = true; try { const updated = await context.updateField(field.id, control.value); field.value = updated.value; control.value = String(updated.value); control.dataset.state = control.value; saved(null); } catch (error) { control.value = String(old); control.dataset.state = control.value; saved(error); } finally { control.disabled = !canEdit(field, context); } }); return control;
}

const COLLECTIONS = {
  attacks:{title:'Attacks & Actions',add:'Add attack',create:()=>({id:crypto.randomUUID(),name:'',ability:'strength',proficiency:'PROFICIENT',bonus:0,damage:'',damageType:'',notes:''}),controls:[['name','Name','text'],['ability','Ability','ability'],['proficiency','Proficiency','proficiency'],['bonus','Other bonus','number'],['damage','Damage','text'],['damageType','Damage type','text'],['notes','Notes','textarea',true]]},
  equipment:{title:'Equipment',add:'Add equipment',create:()=>({id:crypto.randomUUID(),name:'',quantity:1,equipped:false,notes:''}),controls:[['name','Item','text'],['quantity','Quantity','number'],['equipped','Equipped','checkbox'],['notes','Notes','textarea',true]]},
  features:{title:'Features & Traits',add:'Add feature',create:()=>({id:crypto.randomUUID(),name:'',source:'',description:'',usesCurrent:0,usesMaximum:0,reset:'NONE'}),controls:[['name','Name','text'],['source','Source','text'],['usesCurrent','Uses remaining','number'],['usesMaximum','Maximum uses','number'],['reset','Resets','reset'],['description','Description','textarea',true]]},
  'proficiencies-languages':{title:'Proficiencies & Languages',add:'Add proficiency or language',create:()=>({id:crypto.randomUUID(),name:'',type:'OTHER',notes:''}),controls:[['name','Name','text'],['type','Type','kind'],['notes','Notes','textarea',true]]},
};

function entryControl(spec, entry, save, disabled) {
  const [key,label,type,wide] = spec; let control;
  const choices = type === 'ability' ? ABILITIES.map(([value,text])=>[value,text]) : type === 'proficiency' ? [['NONE','None'],['PROFICIENT','Proficient'],['EXPERTISE','Expertise']] : type === 'reset' ? [['NONE','None'],['SHORT_REST','Short rest'],['LONG_REST','Long rest']] : type === 'kind' ? [['LANGUAGE','Language'],['ARMOR','Armor'],['WEAPON','Weapon'],['TOOL','Tool'],['OTHER','Other']] : null;
  if (choices) { control=el('select'); for (const [value,text] of choices) { const option=el('option','',text); option.value=value; control.appendChild(option); } control.value=entry[key]; }
  else if (type === 'textarea') { control=el('textarea'); control.rows=2; control.value=entry[key]??''; }
  else { control=el('input'); control.type=type; if(type==='checkbox') control.checked=Boolean(entry[key]); else control.value=entry[key]??''; }
  control.disabled=disabled; control.addEventListener('change',()=>{entry[key]=type==='number'?Number(control.value):type==='checkbox'?control.checked:control.value; void save();}); return labeled(label,control,wide);
}

function collectionSection(field, context, report, values) {
  const config=COLLECTIONS[field.key], section=el('section','panel section'), list=el('div','collection'); section.append(el('h3','',config.title),list); let collection=normalizeCollection(field.value), queued=false;
  async function save(){if(queued)return;queued=true;try{const updated=await context.updateField(field.id,collection);field.value=updated.value;collection=normalizeCollection(updated.value);report(null);}catch(error){report(error);}finally{queued=false;}}
  function draw(){list.replaceChildren();if(!collection.entries.length)list.append(el('p','empty','Nothing recorded yet.'));for(const entry of collection.entries){const card=el('article','entry'),grid=el('div','entry-grid');for(const spec of config.controls)grid.append(entryControl(spec,entry,save,!canEdit(field,context)));card.append(grid);if(field.key==='attacks'){const total=derivedModifier(numberValue(values().get(`ability-${entry.ability}`),10),entry.proficiency,numberValue(values().get('character-level'),1))+Number(entry.bonus||0);card.prepend(el('div','label',`Attack modifier ${signed(total)}`));}if(canEdit(field,context)){const actions=el('div','actions'),remove=el('button','','Remove');remove.type='button';remove.onclick=()=>{collection.entries=collection.entries.filter((item)=>item.id!==entry.id);draw();void save();};actions.append(remove);card.append(actions);}list.append(card);}if(canEdit(field,context)){const add=el('button','primary',config.add);add.type='button';add.onclick=()=>{collection.entries.push(config.create());draw();void save();};list.append(add);}}
  draw();return{section,redraw:draw,refresh(value){collection=normalizeCollection(value);draw();}};
}

function renderSheet(root, context) {
  root.replaceChildren();root.dataset.dnd5eSheet='';installStyles(root);let fields=asMap(context.fields);const sheet=el('div','sheet'),status=el('p','status',context.permissions.canEdit?'All changes save to the character.':'View only');status.setAttribute('role','status');
  const report=(error)=>{status.dataset.error=error?'true':'false';status.textContent=error?(error.message||'Unable to save'):'Saved';};const derived=[];const saved=(error)=>{report(error);derived.forEach((refresh)=>refresh());};const refreshers=new Map();
  const header=el('header','panel header'),identity=el('div');identity.append(el('h2','',context.character.title),el('p','kicker','D&D 5e character sheet'));header.append(identity,labeled('Level',inputFor(fields.get('character-level'),context,saved)));const inspirationField=fields.get('inspiration'),inspiration=el('input');inspiration.type='checkbox';inspiration.checked=inspirationField.value===true;inspiration.disabled=!canEdit(inspirationField,context);inspiration.onchange=async()=>{try{const updated=await context.updateField(inspirationField.id,inspiration.checked);inspirationField.value=updated.value;report(null);}catch(error){inspiration.checked=!inspiration.checked;report(error);}};header.append(labeled('Inspiration',inspiration));sheet.append(header);const identityDetails=el('section','panel section'),identityGrid=el('div','two');for(const [key,label] of [['character-class','Class'],['character-subclass','Subclass'],['character-background','Background'],['experience-points','Experience Points']])identityGrid.append(labeled(label,inputFor(fields.get(key),context,saved,key==='experience-points'?'number':'text')));identityGrid.append(labeled('Alignment',selectFor(fields.get('character-alignment'),context,[['LAWFUL_GOOD','Lawful Good'],['NEUTRAL_GOOD','Neutral Good'],['CHAOTIC_GOOD','Chaotic Good'],['LAWFUL_NEUTRAL','Lawful Neutral'],['TRUE_NEUTRAL','True Neutral'],['CHAOTIC_NEUTRAL','Chaotic Neutral'],['LAWFUL_EVIL','Lawful Evil'],['NEUTRAL_EVIL','Neutral Evil'],['CHAOTIC_EVIL','Chaotic Evil'],['UNALIGNED','Unaligned']],saved)));identityDetails.append(el('h3','','Character'),identityGrid);sheet.append(identityDetails);
  const page=el('main','page-grid'),left=el('div','column'),abilities=el('section','abilities'),abilityOutputs=new Map(),derivedRows=[];
  function derivedRow(key,label,abbr,ability,expertise){const field=fields.get(key),row=el('label','derived'),select=selectFor(field,context,(expertise?['NONE','PROFICIENT','EXPERTISE']:['NONE','PROFICIENT']).map((value)=>[value,value]),saved,true),output=el('output');const refresh=()=>{const current=fields.get(key)??field;output.textContent=signed(derivedModifier(numberValue(fields.get(`ability-${ability}`),10),current.value,numberValue(fields.get('character-level'),1)));select.dataset.state=String(current.value);};row.append(select,output,el('span','',label),el('span','tag',abbr));return{row,refresh};}
  for(const [ability,label,abbr] of ABILITIES){const card=el('article','panel ability'),score=el('label','score'),modifier=el('output','modifier');abilityOutputs.set(ability,modifier);score.append(el('span','label',label),modifier,inputFor(fields.get(`ability-${ability}`),context,saved));card.append(score);const rows=el('div','derived-list'),save=derivedRow(`save-${ability}`,`${label} save`,abbr,ability,false);rows.append(save.row);derivedRows.push(save);for(const [skill,skillLabel] of SKILLS.filter((item)=>item[2]===ability)){const result=derivedRow(`skill-${skill}`,skillLabel,abbr,ability,true);rows.append(result.row);derivedRows.push(result);}card.append(rows);abilities.append(card);}left.append(abilities);
  const awareness=el('section','panel section');awareness.append(el('h3','','Awareness'));const passive=el('output','modifier'),senses=inputFor(fields.get('senses'),context,saved,'textarea');senses.rows=2;awareness.append(labeled('Passive Perception',passive),labeled('Senses',senses));left.append(awareness);page.append(left);
  const center=el('div','column'),combat=el('section','panel section'),combatTop=el('div','combat-top');combat.append(el('h3','','Combat'));const ac=el('div','panel stat');ac.append(el('span','label','Armor Class'),inputFor(fields.get('combat-ac'),context,saved));const initiative=el('div','panel stat'),initiativeOutput=el('output');initiative.append(el('span','label','Initiative'),initiativeOutput,inputFor(fields.get('combat-initiative-bonus'),context,saved));const speed=el('div','panel stat');speed.append(el('span','label','Speed'),inputFor(fields.get('combat-speed'),context,saved));combatTop.append(ac,initiative,speed);combat.append(combatTop);const hp=el('div','two');for(const [key,label] of [['hp-current','Current HP'],['hp-maximum','Maximum HP'],['hp-temporary','Temporary HP']])hp.append(labeled(label,inputFor(fields.get(key),context,saved),key==='hp-temporary'));combat.append(hp);const hitDice=el('div','two');hitDice.append(labeled('Hit Die',selectFor(fields.get('hit-die'),context,['D6','D8','D10','D12'].map((value)=>[value,value]),saved)),labeled('Hit Dice Remaining',inputFor(fields.get('hit-dice-current'),context,saved)));combat.append(hitDice);const death=el('div','two');death.append(labeled('Death Save Successes',inputFor(fields.get('death-save-successes'),context,saved)),labeled('Death Save Failures',inputFor(fields.get('death-save-failures'),context,saved)));combat.append(death);center.append(combat);
  for(const key of ['attacks','equipment']){const view=collectionSection(fields.get(key),context,report,()=>fields);center.append(view.section);refreshers.set(key,view.refresh);if(key==='attacks')derived.push(view.redraw);}const coins=el('section','panel section'),coinGrid=el('div','entry-grid');coins.append(el('h3','','Coinage'));for(const [key,label] of [['currency-copper','CP'],['currency-silver','SP'],['currency-electrum','EP'],['currency-gold','GP'],['currency-platinum','PP']])coinGrid.append(labeled(label,inputFor(fields.get(key),context,saved)));coins.append(coinGrid);center.append(coins);page.append(center);const right=el('div','column');for(const key of ['proficiencies-languages','features']){const view=collectionSection(fields.get(key),context,report,()=>fields);right.append(view.section);refreshers.set(key,view.refresh);}page.append(right);sheet.append(page,status);root.append(sheet);
  const refreshDerived=()=>{for(const [ability] of ABILITIES)abilityOutputs.get(ability).textContent=signed(abilityModifier(numberValue(fields.get(`ability-${ability}`),10)));for(const row of derivedRows)row.refresh();passive.textContent=String(10+derivedModifier(numberValue(fields.get('ability-wisdom'),10),fields.get('skill-perception').value,numberValue(fields.get('character-level'),1)));initiativeOutput.textContent=signed(abilityModifier(numberValue(fields.get('ability-dexterity'),10))+numberValue(fields.get('combat-initiative-bonus'),0));};derived.push(refreshDerived);refreshDerived();
  const controls=new Map([...root.querySelectorAll('[aria-label]')].map((control)=>[control.getAttribute('aria-label'),control]));async function refresh(){if(context.signal.aborted||document.visibilityState==='hidden')return;try{const response=await fetch(`/api/campaigns/${encodeURIComponent(context.campaign.handle)}/wiki/${encodeURIComponent(context.character.id)}/character-fields`,{credentials:'include',signal:context.signal});if(!response.ok)return;const payload=await response.json(),latest=(payload.fields??[]).filter((field)=>field.pluginId===PLUGIN_ID&&field.sourceKey===PAGE_KEY);fields=asMap(latest);for(const field of latest){const control=controls.get(field.label);if(control&&document.activeElement!==control){if(control.type==='checkbox')control.checked=field.value===true;else control.value=String(field.value??'');if(control.matches('.prof'))control.dataset.state=control.value;}refreshers.get(field.key)?.(field.value);}refreshDerived();}catch(error){if(!context.signal.aborted&&error?.name!=='AbortError')console.warn('[dnd-5e] Unable to refresh CharacterFields',error);}}
  const timer=window.setInterval(refresh,10_000),focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{window.clearInterval(timer);window.removeEventListener('focus',focus);};
}

function spellStyles(root) {
  const style=el('style');style.textContent=`
  [data-dnd5e-sheet] .casting-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(13rem,1fr));gap:.7rem}[data-dnd5e-sheet] .casting-source{display:grid;gap:.45rem;padding:.75rem}[data-dnd5e-sheet] .casting-numbers{display:grid;grid-template-columns:repeat(2,1fr);gap:.5rem;text-align:center}[data-dnd5e-sheet] .casting-numbers output{display:block;font-family:ui-serif,Georgia,serif;font-size:1.55rem;font-weight:850}
  [data-dnd5e-sheet] .slot-grid{display:grid;grid-template-columns:repeat(9,minmax(5.5rem,1fr));gap:.5rem}[data-dnd5e-sheet] .slot{display:grid;gap:.3rem;padding:.55rem;text-align:center}[data-dnd5e-sheet] .slot-pair{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.2rem}[data-dnd5e-sheet] .slot input{text-align:center;min-width:0}
  [data-dnd5e-sheet] .spell-levels{columns:3 19rem;column-gap:1rem}[data-dnd5e-sheet] .spell-level{display:inline-grid;width:100%;gap:.55rem;margin:0 0 1rem;break-inside:avoid;padding:.75rem}[data-dnd5e-sheet] .spell-card{display:grid;gap:.4rem;padding:.6rem;border-top:1px solid color-mix(in srgb,currentColor 18%,transparent)}[data-dnd5e-sheet] .spell-flags{display:flex;flex-wrap:wrap;gap:.65rem;font-size:.72rem}[data-dnd5e-sheet] .spell-flags label{display:flex;align-items:center;gap:.25rem}[data-dnd5e-sheet] .spell-flags input{width:auto}
  @media(max-width:900px){[data-dnd5e-sheet] .slot-grid{grid-template-columns:repeat(3,1fr)}[data-dnd5e-sheet] .spell-levels{columns:2 18rem}}@media(max-width:560px){[data-dnd5e-sheet] .slot-grid{grid-template-columns:repeat(2,1fr)}[data-dnd5e-sheet] .spell-levels{columns:1}}
  `;root.append(style);
}

function renderSpellcasting(root, context) {
  root.replaceChildren();root.dataset.dnd5eSheet='';installStyles(root);spellStyles(root);let fields=asMap(context.fields),allFields=new Map(fields);const sheet=el('div','sheet'),status=el('p','status',context.permissions.canEdit?'All changes save to the character.':'View only');status.setAttribute('role','status');const report=(error)=>{status.dataset.error=error?'true':'false';status.textContent=error?(error.message||'Unable to save'):'Saved';};
  const header=el('header','panel header'),identity=el('div');identity.append(el('h2','',`${context.character.title} — Spellcasting`),el('p','kicker','Cantrips and spells by level'));header.append(identity);sheet.append(header);
  const sourceField=fields.get('spellcasting-sources'),spellsField=fields.get('spells');let sources=normalizeCollection(sourceField.value),spells=normalizeCollection(spellsField.value),savingSource=false,savingSpell=false;
  const summarySection=el('section','panel section'),summary=el('div','casting-summary');summarySection.append(el('h3','','Spellcasting Sources'),summary);sheet.append(summarySection);
  async function saveSources(){if(savingSource)return;savingSource=true;try{const updated=await context.updateField(sourceField.id,sources);sourceField.value=updated.value;sources=normalizeCollection(updated.value);report(null);}catch(error){report(error);}finally{savingSource=false;}}
  async function saveSpells(){if(savingSpell)return;savingSpell=true;try{const updated=await context.updateField(spellsField.id,spells);spellsField.value=updated.value;spells=normalizeCollection(updated.value);report(null);}catch(error){report(error);}finally{savingSpell=false;}}
  function sourceSelect(entry){const select=el('select');const none=el('option','','No source');none.value='';select.append(none);for(const source of sources.entries){const option=el('option','',source.name||'Unnamed source');option.value=source.id;select.append(option);}select.value=entry.sourceId;select.disabled=!canEdit(spellsField,context);select.onchange=()=>{entry.sourceId=select.value;void saveSpells();};return select;}
  function drawSources(){summary.replaceChildren();for(const source of sources.entries){const card=el('article','panel casting-source'),grid=el('div','entry-grid');for(const [key,label,type] of [['name','Name','text'],['ability','Ability','ability'],['attackBonus','Attack bonus adjustment','number'],['saveDcBonus','Save DC adjustment','number'],['notes','Notes','textarea']]){let control;if(type==='ability'){control=el('select');for(const [value,text] of ABILITIES){const option=el('option','',text);option.value=value;control.append(option);}control.value=source[key];}else{control=el(type==='textarea'?'textarea':'input');if(type!=='textarea')control.type=type;control.value=source[key]??'';}control.disabled=!canEdit(sourceField,context);control.onchange=()=>{source[key]=type==='number'?Number(control.value):control.value;drawSources();drawSpells();void saveSources();};grid.append(labeled(label,control,key==='notes'));}card.append(grid);const abilityScore=numberValue(allFields.get(`ability-${source.ability}`),10),level=numberValue(allFields.get('character-level'),1),calculated=spellcastingSummary(source,abilityScore,level),numbers=el('div','casting-numbers');const attack=el('div');attack.append(el('span','label','Spell Attack'),el('output','',signed(calculated.attackModifier)));const dc=el('div');dc.append(el('span','label','Save DC'),el('output','',String(calculated.saveDc)));numbers.append(attack,dc);card.append(numbers);if(canEdit(sourceField,context)){const remove=el('button','','Remove source');remove.type='button';remove.onclick=()=>{sources.entries=sources.entries.filter((item)=>item.id!==source.id);for(const spell of spells.entries)if(spell.sourceId===source.id)spell.sourceId='';drawSources();drawSpells();void saveSources();void saveSpells();};card.append(remove);}summary.append(card);}if(!sources.entries.length)summary.append(el('p','empty','Add a casting source such as Wizard / Intelligence or Cleric / Wisdom.'));if(canEdit(sourceField,context)){const add=el('button','primary','Add casting source');add.type='button';add.onclick=()=>{sources.entries.push({id:crypto.randomUUID(),name:'',ability:'intelligence',attackBonus:0,saveDcBonus:0,notes:''});drawSources();drawSpells();void saveSources();};summary.append(add);}}
  const slots=el('section','panel section'),slotGrid=el('div','slot-grid');slots.append(el('h3','','Spell Slots'),slotGrid);for(let level=1;level<=9;level++){const card=el('label','panel slot'),remaining=inputFor(fields.get(`spell-slots-${level}-remaining`),context,report),maximum=inputFor(fields.get(`spell-slots-${level}-maximum`),context,report),pair=el('div','slot-pair');pair.append(remaining,el('span','','/'),maximum);card.append(el('span','label',`Level ${level}`),pair);slotGrid.append(card);}sheet.append(slots);
  const levels=el('div','spell-levels');sheet.append(levels,status);root.append(sheet);
  function spellControl(spell,key,label,type,wide=false){let control;if(type==='source')control=sourceSelect(spell);else if(type==='checkbox'){control=el('input');control.type='checkbox';control.checked=spell[key];control.disabled=!canEdit(spellsField,context);control.onchange=()=>{spell[key]=control.checked;void saveSpells();};return control;}else{control=el(type==='textarea'?'textarea':'input');if(type!=='textarea')control.type=type;control.value=spell[key]??'';control.disabled=!canEdit(spellsField,context);control.onchange=()=>{spell[key]=control.value;void saveSpells();};}return labeled(label,control,wide);}
  function drawSpells(){levels.replaceChildren();for(let level=0;level<=9;level++){const section=el('section','panel spell-level'),title=el('h3','',level===0?'Cantrips':`Level ${level}`);section.append(title);for(const spell of spells.entries.filter((item)=>item.level===level)){const card=el('article','spell-card'),grid=el('div','entry-grid');for(const spec of [['name','Name','text'],['school','School','text'],['sourceId','Casting source','source'],['castingTime','Casting time','text'],['range','Range','text'],['components','Components','text'],['duration','Duration','text'],['reference','Source / reference','text'],['notes','Notes','textarea',true]])grid.append(spellControl(spell,...spec));const flags=el('div','spell-flags');for(const [key,label] of [['prepared','Prepared'],['ritual','Ritual'],['concentration','Concentration']]){const wrapper=el('label');wrapper.append(spellControl(spell,key,label,'checkbox'),document.createTextNode(label));flags.append(wrapper);}card.append(grid,flags);if(canEdit(spellsField,context)){const remove=el('button','','Remove');remove.type='button';remove.onclick=()=>{spells.entries=spells.entries.filter((item)=>item.id!==spell.id);drawSpells();void saveSpells();};card.append(remove);}section.append(card);}if(canEdit(spellsField,context)){const add=el('button','primary',level===0?'Add cantrip':`Add level ${level} spell`);add.type='button';add.onclick=()=>{spells.entries.push({id:crypto.randomUUID(),name:'',level,school:'',sourceId:'',prepared:false,ritual:false,concentration:false,castingTime:'',range:'',components:'',duration:'',reference:'',notes:''});drawSpells();void saveSpells();};section.append(add);}levels.append(section);}}
  drawSources();drawSpells();
  async function refresh(){if(context.signal.aborted||document.visibilityState==='hidden')return;try{const response=await fetch(`/api/campaigns/${encodeURIComponent(context.campaign.handle)}/wiki/${encodeURIComponent(context.character.id)}/character-fields`,{credentials:'include',signal:context.signal});if(!response.ok)return;const payload=await response.json(),latest=payload.fields??[];allFields=asMap(latest);fields=asMap(latest.filter((field)=>field.pluginId===PLUGIN_ID&&field.sourceKey==='spellcasting'));sources=normalizeCollection(fields.get('spellcasting-sources')?.value);spells=normalizeCollection(fields.get('spells')?.value);drawSources();drawSpells();for(let level=1;level<=9;level++)for(const suffix of ['remaining','maximum']){const field=fields.get(`spell-slots-${level}-${suffix}`),control=root.querySelector(`[aria-label="${CSS.escape(field.label)}"]`);if(control&&document.activeElement!==control)control.value=String(field.value??0);}}catch(error){if(!context.signal.aborted&&error?.name!=='AbortError')console.warn('[dnd-5e] Unable to refresh spellcasting fields',error);}}
  void refresh();const timer=window.setInterval(refresh,10_000),focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{window.clearInterval(timer);window.removeEventListener('focus',focus);};
}

export function register(registry) {
  registry.registerCharacterPageRenderer({key:PAGE_KEY,render:renderSheet});
  registry.registerCharacterPageRenderer({key:'spellcasting',render:renderSpellcasting});
}
