export const CHARACTER_GENERATOR_CSS = `
.cg-app{--cg-accent:#b99cff;color:var(--color-foreground,inherit);display:grid;gap:1rem}
.cg-toolbar{position:sticky;top:.75rem;z-index:20;display:flex;flex-wrap:wrap;align-items:end;gap:.75rem;padding:1rem;border:1px solid var(--color-border,currentColor);border-radius:1rem;background:color-mix(in srgb,var(--color-elevated,#18161f) 94%,transparent);box-shadow:0 12px 30px #0002;backdrop-filter:blur(14px)}
.cg-control{display:grid;gap:.3rem;min-width:10rem}.cg-control span,.cg-kicker{font-size:.68rem;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--color-muted,#999)}
.cg-select,.cg-textarea{border:1px solid var(--color-border,#555);border-radius:.65rem;background:var(--color-surface,#191820);color:inherit;padding:.62rem .75rem;font:inherit}.cg-select:focus,.cg-textarea:focus,.cg-value-edit:focus{outline:2px solid var(--cg-accent);outline-offset:2px}
.cg-actions{display:flex;gap:.5rem;margin-left:auto}.cg-btn{min-height:2.55rem;border:1px solid var(--color-border,#555);border-radius:.7rem;background:var(--color-surface,#24212d);color:inherit;padding:.55rem .85rem;font-weight:650;cursor:pointer}.cg-btn:hover{border-color:var(--cg-accent)}.cg-btn-primary{border-color:transparent;background:var(--cg-accent);color:#17121f}.cg-btn-icon{display:grid;place-items:center;width:2.1rem;height:2.1rem;padding:0;border-radius:.55rem}.cg-btn[aria-pressed=true]{background:color-mix(in srgb,var(--cg-accent) 20%,var(--color-surface,#24212d));border-color:var(--cg-accent)}
.cg-intro{display:flex;align-items:end;justify-content:space-between;gap:1rem}.cg-intro h2{margin:.2rem 0 0;font-size:clamp(1.35rem,3vw,2rem);font-family:var(--font-display,inherit)}.cg-intro p{margin:.25rem 0 0;color:var(--color-muted,#aaa)}
.cg-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;align-items:start}.cg-card{border:1px solid var(--color-border,#555);border-radius:1rem;background:color-mix(in srgb,var(--color-elevated,#1d1b24) 70%,transparent);overflow:hidden}.cg-card-head{padding:.9rem 1rem;border-bottom:1px solid color-mix(in srgb,var(--color-border,#555) 65%,transparent)}.cg-card-head h3{margin:0;font-size:1rem}.cg-card-head p{margin:.25rem 0 0;color:var(--color-muted,#aaa);font-size:.8rem}.cg-fields{display:grid}.cg-field{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.65rem;align-items:center;padding:.8rem 1rem;border-top:1px solid color-mix(in srgb,var(--color-border,#555) 38%,transparent)}.cg-field:first-child{border-top:0}.cg-label{display:block;margin-bottom:.2rem;color:var(--color-muted,#aaa);font-size:.72rem}.cg-value{width:100%;border:0;background:transparent;color:inherit;padding:0;text-align:left;font:600 0.94rem/1.35 inherit;cursor:pointer}.cg-value:hover{text-decoration:underline;text-decoration-color:var(--cg-accent);text-underline-offset:.2rem}.cg-placeholder{color:var(--color-muted,#888);font-style:italic;font-weight:400}.cg-value-edit{width:100%;border:0;border-bottom:1px solid var(--cg-accent);background:transparent;color:inherit;padding:.15rem 0;font:600 .94rem inherit}.cg-field-actions{display:flex;gap:.3rem}.cg-field[data-locked=true]{background:color-mix(in srgb,var(--cg-accent) 6%,transparent)}
.cg-custom{border:1px solid var(--color-border,#555);border-radius:.85rem;background:color-mix(in srgb,var(--color-surface,#191820) 55%,transparent)}.cg-custom summary{cursor:pointer;padding:.75rem 1rem;font-weight:650}.cg-custom-body{display:grid;grid-template-columns:1fr 1fr;gap:1rem;padding:0 1rem 1rem}.cg-custom-group{display:grid;gap:.5rem}.cg-custom-options{display:flex;gap:1rem;font-size:.8rem;color:var(--color-muted,#aaa)}.cg-textarea{min-height:5rem;resize:vertical}
.cg-sr{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media(max-width:900px){.cg-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cg-actions{width:100%;margin-left:0}.cg-actions .cg-btn-primary{flex:1}}
@media(max-width:620px){.cg-toolbar{position:static;align-items:stretch}.cg-control{min-width:calc(50% - .5rem);flex:1}.cg-grid{grid-template-columns:1fr}.cg-custom-body{grid-template-columns:1fr}.cg-intro{align-items:start;flex-direction:column}.cg-actions{display:grid;grid-template-columns:1fr auto}.cg-btn{min-height:2.8rem}}
`;
